version: "3.9"

services:
  jageocoder-server:
    container_name: jageocoder-server
    build:
      dockerfile: Dockerfile
      args:
        - DIC_URL=https://www.info-proto.com/static/jageocoder/latest/v2/jukyo_all_v20.zip
    shm_size: 512m
    volumes:
      - type: volume
        source: jageocoder-server-data
        target: /data
    ports:
      - 5000:5000

volumes:
  jageocoder-server-data: {}
