version: "3.9"

services:
  jageocoder-server:
    container_name: jageocoder-server
    build:
      dockerfile: Dockerfile
      args:
        - DICFILE=jukyo_all_v20.zip
    shm_size: 512m
    volumes:
      - type: volume
        source: jageocoder-server-db
        target: /db
      - type: bind
        source: ./data
        target: /data
    ports:
      - 5000:5000

volumes:
  jageocoder-server-db: {}
