name: Compatibility Check

on: [push, pull_request]

jobs:
  compat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt
      - run: python -c "import server.app"
        working-directory: ${{ github.workspace }}
        env:
          JAGEOCODER_SERVER_URL: "https://jageocoder.info-proto.com/jsonrpc"
